### ISSUE TITLE
Building on Debian, libraries in ext aren't used properly(?)

### ISSUE THREAD

**Issue by SolraBizna** [arescentral/antares#188]
I'm building on Debian 9.0, and there were several packages I had to install that weren't caught correctly by configure: `libzip-dev`, `libmodplug-dev`, `libglfw3-dev`, `libsndfile-dev`.

For each one of these packages, configure would fail with output like this:

```
checking for gn...            ok
checking host os...           linux
checking target os...         linux
checking Linux distro...      debian 9.0  (untested)
checking for clang...         ok
checking for ninja...         ok
checking for pkg-config...    ok
checking for gl...            ok
checking for glu...           ok
checking for neon...          ok
checking for openal...        ok
checking for x11...           ok
checking for xcursor...       ok
checking for xinerama...      ok
checking for xrandr...        ok
checking for xxf86vm...       ok
checking for zlib...          ok
configure mode...             opt
generating build.ninja...ERROR at //build/lib/pkg_config.gni:9:11: Script returned non-zero exit code.
  flags = exec_script(script, [ invoker.lib ], "scope")
          ^----------
Current dir: /home/sbizna/antares/out/linux/opt/
Command: python -- /home/sbizna/antares/build/lib/scripts/pkg_config.py glfw3
Returned 1.
stderr:

Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
Traceback (most recent call last):
  File "/home/sbizna/antares/build/lib/scripts/pkg_config.py", line 29, in <module>
    main()
  File "/home/sbizna/antares/build/lib/scripts/pkg_config.py", line 24, in main
    values = subprocess.check_output(["pkg-config", flag, "--", library])
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pkg-config', '--libs-only-l', '--', 'glfw3']' returned non-zero exit status 1

See //ext/glfw/BUILD.gn:120:3: whence it was called.
  pkg_config("libglfw_public") {
  ^-----------------------------
See //BUILD.gn:526:5: which caused the file to be included.
    "//ext/glfw:libglfw",
    ^-------------------
     failed
```

Compared to when, earlier, some dependencies known to configure were missing:

```
checking for gn...            ok
checking host os...           linux
checking target os...         linux
checking Linux distro...      debian 9.0  (untested)
checking for clang...         ok
checking for ninja...         missing
checking for ninja-build...   missing
checking for pkg-config...    ok
checking for gl...            ok
checking for glu...           ok
checking for neon...          missing
checking for openal...        ok
checking for x11...           ok
checking for xcursor...       ok
checking for xinerama...      ok
checking for xrandr...        ok
checking for xxf86vm...       ok
checking for zlib...          ok

missing dependencies: ninja neon

On Ubuntu, you can install them with:

    $ sudo apt-get install ninja-build libneon27-dev
```

(Which is just about the friendliest `configure` failure I've ever seen.)

It looks like it's trying to use the libraries in `ext` but failing somehow.

**Comment by sfiera** [comment]
On Linux it's supposed to use system libraries by default (the build files in ext/* are just running pkg-config in this case). The whole ext/ stuff is really just for Mac, where the libraries need to be bundled with the app.

I fixed this on the release branch but haven't yet merged that back to master. If you pull sfiera/antares:release/0.8.2 it should be fine, though it seems you're already sorted. (It's really past time I finalized that release…)
